[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.0",
    "pydantic>=2.11.5",
    "pytest>=8.4.0",
    "textual>=3.3.0",
    "tinydb>=4.8.2",
]
